apiVersion: apps/v1
kind: Deployment
metadata:
  name: job4j-devops-k8s
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: mihanchik94/job4j_devops-k8s_simple_docker:v1
          ports:
            - containerPort: 8080
